### ISSUE TITLE
Display something on power up

### ISSUE THREAD

**Issue by josephernest** [sparkfun/Serial7SegmentDisplay#16]
I'm using the 7segment display with a raspberry pi.
During the Linux booting time (~15 seconds), the 7segment display **displays nothing**.

Is it possible to show  "___", "----"  once it is powered up?

So the user will know the system is "booting".

How to do this?

**Comment by jimblom** [comment]
Sure, this is a relatively simple modification. The four variable assignments starting [here](https://github.com/sparkfun/Serial7SegmentDisplay/blob/master/firmware/Serial%207-Segment%20Display/Serial_7_Segment_Display_Firmware/Serial_7_Segment_Display_Firmware.ino#L83) set what the display shows on start-up.

For example, to make the display show "----", swap in these four lines of code:

    display.digits[0] = '-';
    display.digits[1] = '-';
    display.digits[2] = '-';
    display.digits[3] = '-';

**Comment by josephernest** [comment]
So do you mean it should *already* display something on power up?  (it seems, in your code, that `1234` should be displayed on power up, or am I wrong?).

I just tried by connecting +5V and GND only  (and no serial, no I2C), but nothing is displayed.

When exactly should these default letters happen? Really when +5V comes ? or is there another trigger for the "startup"?
