### ISSUE TITLE
Refresh rate / flicker

### ISSUE THREAD

**Issue by josephernest** [sparkfun/Serial7SegmentDisplay#17]
I'm currently filming my hardware project (including a 7seg display) with a camera. 

The result is *flickering* because probably the refresh rate does not fit well with 24fps or 30fps of my camera. 

Any idea on how to change refresh rate of Serial7SegmentDisplay?

**Comment by jimblom** [comment]
You'll have to modify the [SevSeg library](https://github.com/sparkfun/SevSeg) to achieve this. The constant `FRAMEPERIOD`, defined [here](https://github.com/sparkfun/SevSeg/blob/master/src/SevSeg.h#L28) is probably the best place to begin experimenting. Try turning it to somewhere between 500-1000.

**Comment by josephernest** [comment]
In fact the problem has been solved by changing the shutter speed of the
camera (didn't know it was possible in "Movie" mode).
Setting shutter speed to 1/30 or 1/50 worked.
