### ISSUE TITLE
Error check

### ISSUE THREAD

**Issue by josephernest** [sparkfun/Serial7SegmentDisplay#18]
I use Serial7SegmentDisplay with a RaspberryPi. It works both with I2C, and with Serial.

Everything is fine 90% of the time. But sometimes, some characters are not well sent/received by the display, and one character is missing. This is happening for some other people (I found on some forums).

Could we add basic error check, so that if a byte is not well received, the serial or SPI interface will resend?

Tried:

* sleep 5 ms between each byte send, it improves a bit but does not solve 100%
* change bps rate, but doesn't change anything

**Comment by glebtv** [comment]
https://github.com/sparkfun/Serial7SegmentDisplay/blob/master/firmware/Serial%207-Segment%20Display/Serial_7_Segment_Display_Firmware/Serial_7_Segment_Display_Firmware.ino#L247

I think it's a bug somewhere here, whenever you set a 0x76 to the display it clears and moves cursor
Example (setting brightness to 117)
```
s7sSendStringI2C("TEST");
delay(500);
Wire.beginTransmission(s7sAddress);
Wire.write(0x7A);  // Set brightness command byte
Wire.write(0x76);  // brightness data byte
Wire.endTransmission();
delay(500);
```

**Comment by josephernest** [comment]
@glebtv What do you mean?

Do you think it's impossible to send a 0x76 value for brightness for example? It will always clear the display?

I cannot test now, but are you sure?
@jimblom what do you think?

**Comment by glebtv** [comment]
Yes, the firmware code checks for reset before checking for anything else so sending 0x76 (reset) as brightness or any other DATA it resets the display - which gives exactly the effect described in this issue - a couple characters will be missing from display. 
I found that accidentally by testing different brightness levels in a loop.

See code I linked https://github.com/sparkfun/Serial7SegmentDisplay/blob/master/firmware/Serial%207-Segment%20Display/Serial_7_Segment_Display_Firmware/Serial_7_Segment_Display_Firmware.ino#L247

**Comment by jimblom** [comment]
Sorry to be so late on this. I've added a check for a current commandMode before clearing the display. That seems to fix the bug.
