### ISSUE TITLE
Technical data for Sparkfun PCB missing -- measures provided

### ISSUE THREAD

**Issue by sorenoneill** [sparkfun/Serial7SegmentDisplay#23]
I have searched but not been able to find the technical data for the PCB dimensions. Data is available for the 7-segment display itself, but not the PCB.

These are my measures using a caliper:

width: 41.3mm
depth: 23.5mm
thickness: 1.6mm

stand-off holes diameter: 3.0mm
stand-off holes width offset (to center of hole): 5.2 (possibly should be 0.2in)
stand-off holes depth offset (to center of hole): 2.7 (possibly should be 0.1in)

**Comment by bboyho** [comment]
Hi,

Thanks for the measurements. The dimensions (except for the PCB thickness) are actually provided in inches under the [hardware specifications under this repository's Wiki](https://github.com/sparkfun/Serial7SegmentDisplay/wiki/Hardware-specifications#physical-dimensions):

[![Serial Enabled 7 Segment Display](https://dlnmh9ip6v2uc.cloudfront.net/tutorialimages/Serial7SegmentDisplay/dimensions_large.png)](https://github.com/sparkfun/Serial7SegmentDisplay/wiki/Hardware-specifications#physical-dimensions)

I'll be closing this issue out. =)
